get-identity:
	aws sts get-caller-identity

init:
	terraform init -upgrade

state-list:
	terraform state list

plan:
	terraform plan

apply:
	terraform apply -auto-approve

destroy:
	terraform destroy -auto-approve

fmt:
	terraform fmt -recursive

validate:
	terraform validate -recursive

