kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-sc-default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  datastoreurl: "ds:///vmfs/volumes/6707f69e-239123a1-a491-d4ae528b68cc/"
  fsType: ext4

