apiVersion: v1
kind: Secret
metadata:
  name: vsphere-config-secret
  namespace: vmware-system-csi
type: Opaque
stringData:
  csi-vsphere.conf: |
    [Global]
    cluster-id = "tools-k8s-dev-cluster"

    [VirtualCenter "10.89.65.21"]
    insecure-flag = "true"
    user = "administrator@vsphere.local"
    password = "SlickSci87!"
    datacenters = "dc-east"
