fullnameOverride: "metallb"

controller:
  enabled: true
  logLevel: info
  image: 
    repository: quay.io/metallb/controller
    tag: 
    pullPolicy:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    fsGroup: 65534

speaker:
  enabled: false
  logLevel: info
  image:
    repository: quay.io/metallb/speaker
    tag:

